gaze_config:
  history_duration: 0.15
  update_interval: 0.02
  point_radius: 50
  point_alpha: 20
  clear_radius: 55
  color_r: 230
  color_g: 20
  color_b: 20
  gaussian_sigma_ratio: 1.0
  window_alpha: 20
mouse_control_config:
  dead_zone: 250
  max_speed: 100
  smoothing: 0.5
  y_speed_coef: 1.3
  head_coef: 5
  lock_head_duration: 2
  wheel_head_coef: 100
wheel_config:
  radius: 1000
  font_size: 14
  font: Arial
real_action_config:
  scroll_coef: 1.0
  sys_mode: game_cs
  show_gaze: false
  mouse_control: true
  key_control: true
integrated_config:
  weights: my_model_arch/cpu_fast/cpu_convert/mobileone_s0_224_fp16_pnnx.ncnn.param
  regression_model_type: lassocv
  regression_model_path: null
  arch: mobileone_s0
  device: cpu
  cam_id: 0
  num_points: 9
  every_point_has_n_images: 25
  images_freq: 15
  each_point_wait_time: 1000
  edge: 0.05
  radius: 20
  func: sequence
  window_name: track
  render_in_eval: false
  kalman_filter_std_measurement: 2.0
  Q_coef: 0.01
  dt: 0.04
  screen_size:
  - 0
  - 0
  pred_point_color:
  - 0
  - 0
  - 0
  true_point_color:
  - 0
  - 0
  - 0
  gaze_bias:
  - 0
  - 0
head_angles_center:
  yaw: 0.0
  pitch: 0.0
  roll: 0.0
head_angles_scale:
  yaw: 88.0
  pitch: 88.0
  roll: 88.0
expression_evaluator_config:
  expressions:
    numlock:
      conditions:
      - feature: jawOpen
        operator: '>'
        threshold: 0.4
      - feature: jawLeft
        operator: <
        threshold: 0.1
      - feature: jawRight
        operator: <
        threshold: 0.1
      combine: AND
    num0:
      conditions:
      - feature: mouthRollLower
        operator: '>'
        threshold: 0.45
      - feature: mouthRollUpper
        operator: '>'
        threshold: 0.45
      combine: AND
    num1:
      conditions:
      - feature: mouthSmileLeft
        operator: BETWEEN
        min: 0.0
        max: 0.0
      - feature: mouthSmileLeft
        operator: DIFF>
        threshold: 0.15
        compare_to: mouthSmileLeft
      combine: AND
    num2:
      conditions:
      - feature: mouthSmileLeft
        operator: '>'
        threshold: 0.45
      - feature: mouthSmileRight
        operator: '>'
        threshold: 0.45
      - feature: mouthSmileLeft
        operator: DIFF<
        threshold: 0.2
        compare_to: mouthSmileLeft
      combine: AND
    num3:
      conditions:
      - feature: mouthSmileRight
        operator: BETWEEN
        min: 0.0
        max: 0.0
      - feature: mouthSmileRight
        operator: DIFF>
        threshold: 0.15
        compare_to: mouthSmileLeft
      combine: AND
    num4:
      conditions:
      - feature: mouthLeft
        operator: '>'
        threshold: 0.4
      - feature: mouthRight
        operator: <
        threshold: 0.2
      - feature: jawOpen
        operator: <
        threshold: 0.05
      - feature: mouthSmileLeft
        operator: <
        threshold: 0.2
      - feature: mouthSmileRight
        operator: <
        threshold: 0.2
      combine: AND
    num5:
      conditions:
      - feature: mouthPressLeft
        operator: '>'
        threshold: 0.4
      - feature: mouthPressRight
        operator: '>'
        threshold: 0.4
      combine: AND
    num6:
      conditions:
      - feature: mouthRight
        operator: '>'
        threshold: 0.4
      - feature: mouthLeft
        operator: <
        threshold: 0.2
      - feature: jawOpen
        operator: <
        threshold: 0.05
      - feature: mouthSmileLeft
        operator: <
        threshold: 0.2
      - feature: mouthSmileRight
        operator: <
        threshold: 0.2
      combine: AND
    num7:
      conditions:
      - feature: mouthUpperUpLeft
        operator: '>'
        threshold: 0.5
      - feature: mouthUpperUpRight
        operator: '>'
        threshold: 0.5
      - feature: mouthLowerDownLeft
        operator: '>'
        threshold: 0.3
      - feature: mouthLowerDownRight
        operator: '>'
        threshold: 0.3
      combine: AND
    num8:
      conditions:
      - feature: browInnerUp
        operator: '>'
        threshold: 0.8
      combine: AND
    num9:
      conditions:
      - feature: mouthFunnel
        operator: '>'
        threshold: 0.4
      combine: AND
    right_click:
      conditions:
      - feature: jawLeft
        operator: '>'
        threshold: 0.3
      combine: AND
    mid_click:
      conditions:
      - feature: jawRight
        operator: '>'
        threshold: 0.3
      combine: AND
    left_click:
      conditions:
      - feature: mouthPucker
        operator: '>'
        threshold: 0.97
      - feature: mouthFunnel
        operator: <
        threshold: 0.2
      combine: AND
    extra:
      conditions:
      - feature: eyeBlinkLeft
        operator: '>'
        threshold: 0.6
      - feature: eyeBlinkRight
        operator: <
        threshold: 0.25
      combine: AND
  priority_rules:
  - when: num7
    disable:
    - num2
    except: []
  - when: any
    disable:
    - left_click
    except:
    - left_click
key_config:
  game:
    numlock:
      wheel:
      - game
      - type
      - game_cs
      - game_wz
    num0:
      wheel:
      - e
    num1:
      wheel:
      - z
      - x
      - c
    num2:
      wheel:
      - shift
    num3:
      wheel:
      - v
    num4:
      wheel:
      - '1'
      - '2'
      - '3'
      - '4'
    num5:
      wheel:
      - g
    num6:
      wheel:
      - q
      - r
      - f
      - t
    num7:
      wheel:
      - esc
    num8:
      wheel:
      - space
    num9:
      wheel:
      - ctrl
    left_click:
      wheel:
      - mouse_left
      induce:
        lock_mouse_move:
          duration: 1
    mid_click:
      wheel:
      - mouse_middle
    right_click:
      wheel:
      - mouse_right
    extra:
      wheel:
      - None
    head_up:
      wheel:
      - s
    head_down:
      wheel:
      - w
    head_left:
      wheel:
      - a
    head_right:
      wheel:
      - d
    head_roll_left:
      wheel:
      - scroll_up
    head_roll_right:
      wheel:
      - scroll_down
  game_wz:
    numlock:
      wheel:
      - game
      - type
      - game_cs
      - game_wz
    num0:
      wheel:
      - e
    num1:
      wheel:
      - '1'
    num2:
      wheel:
      - '2'
    num3:
      wheel:
      - '3'
    num4:
      wheel:
      - m
    num5:
      wheel:
      - g
    num6:
      wheel:
      - q
      - r
      - f
      - t
    num7:
      wheel:
      - esc
    num8:
      wheel:
      - space
    num9:
      wheel:
      - ctrl
    left_click:
      wheel:
      - mouse_left
      induce:
        lock_mouse_move:
          duration: 1
    mid_click:
      wheel:
      - mouse_middle
    right_click:
      wheel:
      - mouse_right
    extra:
      wheel:
      - None
    head_up:
      wheel:
      - s
    head_down:
      wheel:
      - w
    head_left:
      wheel:
      - a
    head_right:
      wheel:
      - d
    head_roll_left:
      wheel:
      - scroll_up
    head_roll_right:
      wheel:
      - scroll_down
  game_cs:
    numlock:
      wheel:
      - game
      - type
      - game_cs
      - game_wz
    num0:
      wheel:
      - e
    num1:
      wheel:
      - z
      - x
      - c
    num2:
      wheel:
      - space
    num3:
      wheel:
      - v
    num4:
      wheel:
      - '1'
      - '2'
      - '3'
      - '4'
    num5:
      wheel:
      - g
    num6:
      wheel:
      - q
      - r
      - f
      - t
    num7:
      wheel:
      - esc
    num8:
      wheel:
      - shift
    num9:
      wheel:
      - ctrl
    left_click:
      wheel:
      - mouse_left
      induce:
        lock_mouse_move:
          duration: 0.0
    mid_click:
      wheel:
      - mouse_middle
    right_click:
      wheel:
      - mouse_right
    extra:
      wheel:
      - None
    head_up:
      wheel:
      - s
    head_down:
      wheel:
      - w
    head_left:
      wheel:
      - a
    head_right:
      wheel:
      - d
    head_roll_left:
      wheel:
      - scroll_up
    head_roll_right:
      wheel:
      - scroll_down
  type:
    numlock:
      wheel:
      - game
      - type
      - game_cs
      - game_wz
    num0:
      wheel:
      - keydown
      - keyup
    num1:
      wheel:
      - backspace
    num2:
      wheel:
      - shift
      - ctrl
      - caps
      - tab
      - alt
      - esc
      - fn
      - win
    num3:
      wheel:
      - ctrl+c
      - ctrl+v
      - ctrl+q
      - ctrl+a
      - ctrl+alt
    num4:
      wheel:
      - a
      - b
      - c
      - d
      - e
      - f
      - g
      - h
      - i
      - j
      - k
      - l
      - m
      - n
      - o
      - p
      - q
      - r
      - s
      - t
      - u
      - v
      - w
      - x
      - y
      - z
      - backspace
      - space
      - enter
      layout_type: square
    num5:
      wheel:
      - None
    num6:
      wheel:
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
      - '6'
      - '7'
      - '8'
      - '9'
      - '`'
      - '-'
      - '='
      - '['
      - ']'
      - \
      - ;
      - ''''
      - ','
      - .
      - /
      layout_type: square
    num7:
      wheel:
      - esc
    num8:
      wheel:
      - space
    num9:
      wheel:
      - F1
      - F2
      - F3
      - F4
      - F5
      - F6
      - F7
      - F8
      - F9
      - F10
      - F11
      - F12
    left_click:
      wheel:
      - mouse_left
      induce:
        lock_mouse_move:
          duration: 1
    mid_click:
      wheel:
      - mouse_middle
    right_click:
      wheel:
      - mouse_right
    extra:
      wheel:
      - None
    head_roll_left:
      wheel:
      - scroll_up
    head_roll_right:
      wheel:
      - scroll_down
